apiVersion: apps/v1
kind: Deployment
metadata:
  name: aw-sample
  labels:
    app: aw-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aw-sample
  template:
    metadata:
      labels:
        app: aw-sample
    spec:
      containers:
        - name: aw-sample
          image: 711387135481.dkr.ecr.us-east-1.amazonaws.com/aw-bootcamp-ecr:latest
          ports:
            - containerPort: 80
